### ISSUE TITLE
mzident to protXML

### ISSUE THREAD

**Issue by SimionKreimer** [iracooke/protk-galaxytools#7]
Hi Ira,
I'm very interested in your script for extracting a protXML file from mzidentML results (generated by PeptideShaker) however I am not familiar with Docker or Galaxy. I was wondering if you possibly had a standalone version of the script. Thank you in advance for your help.

Best, Simion

**Comment by iracooke** [comment]
@SimionKreimer for that script you shouldn't need Docker or Galaxy.  Just install the rubygem

``` bash
gem install protk
```

Then

``` bash
mzid_to_protxml.rb -h
```

But that script isn't really production ready yet.  I need to find a way to make it fast.  It's way to slow currently for normal use.  If you are patient you might be able to get some use out it though

**Comment by SimionKreimer** [comment]
Hi Ira, thank you for the quick response. I downloaded protk, and ran mzid_to_protxml.rb on a PeptideShaker result file. It didn't quiet work out because I got all of these errors:

ruby /home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/bin/mzid_to_protxml.rb -o Test.protXML ~/DIA2PRM_1427_2/UF_DIA_Good.mzid
I, [2015-11-12T20:00:59.477297 #19799]  INFO -- : Parsing MzIdentML input file
I, [2015-11-12T20:00:59.667181 #19799]  INFO -- : Converting 7 protein_groups
I, [2015-11-12T20:00:59.667326 #19799]  INFO -- : Output will be written to Test.protXML
I, [2015-11-12T20:00:59.667513 #19799]  INFO -- : Writing group with probability 1.0
/home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/lib/protk/mzidentml_doc.rb:84:in `find': undefined method`find' for nil:NilClass (NoMethodError)
    from /home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/lib/protk/mzidentml_doc.rb:88:in `find'
    from /home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/lib/protk/mzidentml_doc.rb:93:in`get_cvParam'
    from /home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/lib/protk/peptide.rb:53:in `from_mzid'
    from /home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/lib/protk/protein.rb:110:in`block in from_mzid'
    from /home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/lib/protk/protein.rb:110:in `each'
    from /home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/lib/protk/protein.rb:110:in`collect'
    from /home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/lib/protk/protein.rb:110:in `from_mzid'
    from /home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/lib/protk/protein_group.rb:55:in`block in from_mzid'
    from /home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/lib/protk/protein_group.rb:55:in `collect'
    from /home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/lib/protk/protein_group.rb:55:in`from_mzid'
    from /home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/bin/mzid_to_protxml.rb:69:in `block in <main>'
    from /home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/bin/mzid_to_protxml.rb:58:in`each'
    from /home/simion/.gem/ruby/2.2.0/gems/protk-1.4.3/bin/mzid_to_protxml.rb:58:in `<main>'

I've attached the result file, if you're interested in developing this script further. I've been looking for something that can convert output from Search GUI to protXML and pepXML so that it's compatible with some other tools I'm using. So far this is the only protein result parser I found.

Best, Simion
[UF_DIA_Good.mzid.txt](https://github.com/iracooke/protk-galaxytools/files/33527/UF_DIA_Good.mzid.txt)

**Comment by iracooke** [comment]
Hi @SimionKreimer 

Thanks for sending that test file.  The conversion was breaking because you have negative PSM scores in the file.  I fixed that so it would be great if you could see if it works now

To install the latest release (1.4.4.beta1) use

```
gem install protk --pre
```

Just a warning that it will probably still be very slow.

**Comment by SimionKreimer** [comment]
[mzidtoprotXML.txt](https://github.com/iracooke/protk-galaxytools/files/35957/mzidtoprotXML.txt)

Hi Ira,
I was able to execute the updated script, but it generated a xml file containing only one protein identification. There were 28 protein groups identified in the result file above the threshold. So it doesn't seem to be working just yet. I've attached the script output, and the generated protXML file.
[Test.protXML.txt](https://github.com/iracooke/protk-galaxytools/files/35956/Test.protXML.txt)

Best, Simion

**Comment by iracooke** [comment]
Hi @SimionKreimer 

Many thanks for that.  I think I found the bug.  I looked in your file and from what I can tell it only has 7 protein groups.  

If you reinstall with 

``` bash
gem install protk --pre
```

It should now produce a file with 7 protein groups.  You have some 0 probability proteins within these groups so if you want to see those us —minprob=0

**Comment by somakray** [comment]
Hi,

I've a problem while installing  protk in Windows 7 64 bit
gem install protk --pre

Got the following errror. I'm using ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]
with DevKit properly installed. Is this a case of lib-xml related problem as metined here:
http://stackoverflow.com/questions/2915788/libxml-ruby-failed-to-load-at-x86-64

<sup>Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing protk:
        ERROR: Failed to build gem native extension.

```
C:/Ruby22-x64/bin/ruby.exe -r ./siteconf20151202-10036-1yvaqtv.rb extconf.rb
```

</sup>
<sup>
checking for socket() in -lsocket... no
checking for gethostbyname() in -lnsl... no
checking for atan() in -lm... yes
checking for inflate() in -lz... no
checking for inflate() in -lzlib... no
checking for inflate() in -lzlib1... no
checking for inflate() in -llibz... no
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby22-x64/bin/$(RUBY_BASE_NAME)
        --with-iconv-dir
        --without-iconv-dir
        --with-iconv-include
        --without-iconv-include=${iconv-dir}/include
        --with-iconv-lib
        --without-iconv-lib=${iconv-dir}/lib
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --with-socketlib
        --without-socketlib
        --with-nsllib
        --without-nsllib
        --with-mlib
        --without-mlib
        --with-zlib
        --without-zlib
        --with-zliblib
        --without-zliblib
        --with-zlib1lib
        --without-zlib1lib
        --with-libzlib
        --without-libzlib
 extconf failure: need zlib
</sup>
<sup>
extconf failed, exit code 1

Gem files will remain installed in C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/libxml
-ruby-2.8.0 for inspection.
Results logged to C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0
/libxml-ruby-2.8.0/gem_make.out
</sup>

**Comment by iracooke** [comment]
Hi Somakray, 

In this case zlib seems to be missing but you might also be missing other libraries.    Try just installing the libxml-ruby gem first.  If that won't install then protk won't either

**Comment by somakray** [comment]
Hi,
I still can't 
<sub>gem install libxml-ruby</sub>

that too shows the same error:

<sub>extconf failure: need zlib</sub>

**Comment by iracooke** [comment]
Yes. So it's a problem with zlib being missing from your system.
You'll need to install that first.

**Comment by somakray** [comment]
Hi,
Can you provide any pointers on how to install zlib in windows 7?

**Comment by iracooke** [comment]
There are some instructions on the xml4r webpage 

https://github.com/xml4r/libxml-ruby

Have you tried those?

**Comment by somakray** [comment]
I've tried this:
http://vairoj.com/2010/06/installing-libxml-ruby-on-windows-the-painless-way.html
However still he missing Zlib error message appears
